### PR TITLE
fix: local sign options overwrites global sign options

### LINKED ISSUE #304: Local sign options overwrites global sign options
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.21.0

### Plugin version

7.2.0

### Node.js version

18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4.1

### Description

Hello, I'm using fastify-jwt with an implementation of both accessToken and refreshToken. I've observed that when I use a different `expiresIn` value for the refreshToken, it ends up overwriting the global sign options. As a result, when generating the next accessToken, the sign options from the previous refreshToken are used.

### Steps to Reproduce

The generated accessToken on the first call, it will have an expiration of 10 minutes. On the second call, it will have an expiration of 1 day.
From your "onlyCookie" documentation:

```javascript
const fastify = require('fastify')()
const jwt = require('@fastify/jwt')

fastify.register(jwt, {
  secret: 'foobar',
  cookie: {
    cookieName: 'refreshToken',
  },
  sign: {
    expiresIn: '10m'
  }
})

fastify
  .register(require('@fastify/cookie'))

fastify.get('/cookies', async (request, reply) => {

  // On the first call, it will have an expiration of 10 minutes. 
  // On the second call, it will have an expiration of 1 day. 
  const token = await reply.jwtSign({
    name: 'foo'
  })

  const refreshToken = await reply.jwtSign({
    name: 'bar'
  }, {expiresIn: '1d'})

  reply
    .setCookie('refreshToken', refreshToken, {
      domain: 'your.domain',
      path: '/',
      secure: true, // send cookie over HTTPS only
      httpOnly: true,
      sameSite: true // alternative CSRF protection
    })
    .code(200)
    .send({token})
})

fastify.addHook('onRequest', (request) => {
    request.jwtVerify()
    request.jwtVerify({onlyCookie: true})
})

fastify.get('/verifycookie', (request, reply) => {
  reply.send({ code: 'OK', message: 'it works!' })
})

fastify.listen({ port: 3000 }, err => {
  if (err) throw err
})
```

Same when passing sign.expiresIn

```javascript
const refreshToken = await reply.jwtSign(
  {
    name: 'bar',
  },
  {
    sign: {
      expiresIn: '30d',
    },
  }
)
  ```

To solve this we have to pass the sign options also to the accessToken.

```javascript
  const token = await reply.jwtSign({
    name: 'foo'
  }, {expiresIn: '10m'})

  const refreshToken = await reply.jwtSign({
    name: 'bar'
  }, {expiresIn: '1d'})
```

### Expected Behavior

If no custom sign options are provided, the default global ones should be used.
If this is the intended behavior, I believe that the documentation should be updated to provide clarity.

I resolved this issue by implementing changes at:

https://github.com/fastify/fastify-jwt/blob/a4d495c24633f384bd31d5ff93c8ff05a9bda41f/jwt.js#L372

https://github.com/fastify/fastify-jwt/blob/a4d495c24633f384bd31d5ff93c8ff05a9bda41f/jwt.js#L377

by making a copy of the signOptions

```javascript
mergeOptionsWithKey(Object.assign({...signOptions}, localSignOptions), true) 
```

### PR DESCRIPTION
**Pull request by mattiapv**
Closes #304 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: jwt.js [hunk 1]
```diff
@@ -369,12 +369,12 @@ function fastifyJwt (fastify, options, next) {
       const localSignOptions = convertTemporalProps(options.sign)
       // New supported contract, options supports sign and can expand
       options = {
-        sign: mergeOptionsWithKey(Object.assign(signOptions, localSignOptions), true)
+        sign: mergeOptionsWithKey(Object.assign({ ...signOptions }, localSignOptions), true)
```
Comment (jsumners) [inline jwt.js:372]:
```suggestion
        sign: mergeOptionsWithKey(Object.assign({}, signOptions, localSignOptions), true)
```

File: jwt.js [hunk 2]
```diff
@@ -369,12 +369,12 @@ function fastifyJwt (fastify, options, next) {
...
       }
     } else {
       const localOptions = convertTemporalProps(options)
       // Original contract, options supports only sign
-      options = mergeOptionsWithKey(Object.assign(signOptions, localOptions), true)
+      options = mergeOptionsWithKey(Object.assign({ ...signOptions }, localOptions), true)
```
Comment (jsumners) [inline jwt.js:377]:
```suggestion
      options = mergeOptionsWithKey(Object.assign({}, signOptions, localOptions), true)
```

**Review by gurgunday — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm
